# Corvus to C99 High-Performance Transpiler Backend
# Emits optimized ISO C99 code ready for GCC/Clang/MSVC compilation with -O3

import os
import sys

from Compiler_Core.astnodes import (
    ProgramNode, LiteralNode, IdentifierNode, ListNode, TupleNode, DictNode,
    BinOpNode, UnaryOpNode, SafeNavNode, IndexAccessNode, MethodCallNode,
    VarDeclNode, ConstDeclNode, AssignmentNode, BlockNode, IfNode, WhileNode,
    ForNode, BreakNode, ContinueNode, PassNode, GivoutNode, FuncDeclNode,
    LambdaNode, FuncCallNode, ClassDeclNode, GlobalNode, GetNode, AwaitNode,
    TryErrorNode, InputNode, PipelineNode, MatchNode, CaseNode, TernaryNode, FStringNode
)

C_RUNTIME_HEADER = """/* Generated by Corvus C99 Transpiler Engine v4.3.0 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include <math.h>

typedef enum {
    VAL_NULL,
    VAL_BOOL,
    VAL_INT,
    VAL_FLO,
    VAL_STR,
    VAL_LIST,
    VAL_FUNC
} ValType;

struct CorvusVal;

typedef struct CorvusList {
    struct CorvusVal* items;
    size_t length;
    size_t capacity;
} CorvusList;

typedef struct CorvusVal (*CorvusFnPtr)();

typedef struct CorvusVal {
    ValType type;
    union {
        bool b;
        long long i;
        double f;
        char* s;
        CorvusList l;
        CorvusFnPtr fn;
    };
} CorvusVal;

static inline CorvusVal corvus_null(void) {
    CorvusVal v; v.type = VAL_NULL; v.i = 0; return v;
}

static inline CorvusVal corvus_bool(bool b) {
    CorvusVal v; v.type = VAL_BOOL; v.b = b; return v;
}

static inline CorvusVal corvus_int(long long i) {
    CorvusVal v; v.type = VAL_INT; v.i = i; return v;
}

static inline CorvusVal corvus_flo(double f) {
    CorvusVal v; v.type = VAL_FLO; v.f = f; return v;
}

static inline CorvusVal corvus_str(const char* s) {
    CorvusVal v; v.type = VAL_STR;
    if (!s) { v.s = strdup(""); }
    else { v.s = strdup(s); }
    return v;
}

static inline CorvusVal corvus_func(CorvusFnPtr fn) {
    CorvusVal v; v.type = VAL_FUNC; v.fn = fn; return v;
}

static inline bool corvus_is_true(CorvusVal v) {
    switch (v.type) {
        case VAL_NULL: return false;
        case VAL_BOOL: return v.b;
        case VAL_INT:  return v.i != 0;
        case VAL_FLO:  return v.f != 0.0;
        case VAL_STR:  return v.s && strlen(v.s) > 0;
        case VAL_LIST: return v.l.length > 0;
        case VAL_FUNC: return true;
        default: return false;
    }
}

static inline void corvus_print_val(CorvusVal v) {
    switch (v.type) {
        case VAL_NULL: printf("null"); break;
        case VAL_BOOL: printf("%s", v.b ? "true" : "false"); break;
        case VAL_INT:  printf("%lld", v.i); break;
        case VAL_FLO:  printf("%g", v.f); break;
        case VAL_STR:  printf("%s", v.s ? v.s : ""); break;
        case VAL_FUNC: printf("<function>"); break;
        case VAL_LIST: {
            printf("[");
            for (size_t k = 0; k < v.l.length; k++) {
                corvus_print_val(v.l.items[k]);
                if (k + 1 < v.l.length) printf(", ");
            }
            printf("]");
            break;
        }
    }
}

static inline CorvusVal corvus_add(CorvusVal a, CorvusVal b) {
    if (a.type == VAL_INT && b.type == VAL_INT) return corvus_int(a.i + b.i);
    if ((a.type == VAL_INT || a.type == VAL_FLO) && (b.type == VAL_INT || b.type == VAL_FLO)) {
        double da = (a.type == VAL_FLO) ? a.f : (double)a.i;
        double db = (b.type == VAL_FLO) ? b.f : (double)b.i;
        return corvus_flo(da + db);
    }
    if (a.type == VAL_STR || b.type == VAL_STR) {
        char buf1[64], buf2[64];
        const char *s1 = (a.type == VAL_STR) ? a.s : (snprintf(buf1, 64, "%lld", a.i), buf1);
        const char *s2 = (b.type == VAL_STR) ? b.s : (snprintf(buf2, 64, "%lld", b.i), buf2);
        size_t len = strlen(s1) + strlen(s2) + 1;
        char* out = (char*)malloc(len);
        strcpy(out, s1);
        strcat(out, s2);
        CorvusVal v; v.type = VAL_STR; v.s = out;
        return v;
    }
    return corvus_int(a.i + b.i);
}

static inline CorvusVal corvus_sub(CorvusVal a, CorvusVal b) {
    if (a.type == VAL_INT && b.type == VAL_INT) return corvus_int(a.i - b.i);
    double da = (a.type == VAL_FLO) ? a.f : (double)a.i;
    double db = (b.type == VAL_FLO) ? b.f : (double)b.i;
    return corvus_flo(da - db);
}

static inline CorvusVal corvus_mul(CorvusVal a, CorvusVal b) {
    if (a.type == VAL_INT && b.type == VAL_INT) return corvus_int(a.i * b.i);
    double da = (a.type == VAL_FLO) ? a.f : (double)a.i;
    double db = (b.type == VAL_FLO) ? b.f : (double)b.i;
    return corvus_flo(da * db);
}

static inline CorvusVal corvus_div(CorvusVal a, CorvusVal b) {
    double da = (a.type == VAL_FLO) ? a.f : (double)a.i;
    double db = (b.type == VAL_FLO) ? b.f : (double)b.i;
    if (db == 0.0) {
        fprintf(stderr, "[Corvus Panic]: Division by zero.\\n");
        exit(1);
    }
    if (a.type == VAL_INT && b.type == VAL_INT && (a.i % b.i == 0)) {
        return corvus_int(a.i / b.i);
    }
    return corvus_flo(da / db);
}

static inline CorvusVal corvus_mod(CorvusVal a, CorvusVal b) {
    if (b.i == 0) {
        fprintf(stderr, "[Corvus Panic]: Modulo by zero.\\n");
        exit(1);
    }
    return corvus_int(a.i % b.i);
}

static inline CorvusVal corvus_pow(CorvusVal a, CorvusVal b) {
    double da = (a.type == VAL_FLO) ? a.f : (double)a.i;
    double db = (b.type == VAL_FLO) ? b.f : (double)b.i;
    double res = pow(da, db);
    if (a.type == VAL_INT && b.type == VAL_INT && b.i >= 0) return corvus_int((long long)res);
    return corvus_flo(res);
}

static inline CorvusVal corvus_eq(CorvusVal a, CorvusVal b) {
    if (a.type != b.type) return corvus_bool(false);
    if (a.type == VAL_NULL) return corvus_bool(true);
    if (a.type == VAL_BOOL) return corvus_bool(a.b == b.b);
    if (a.type == VAL_INT)  return corvus_bool(a.i == b.i);
    if (a.type == VAL_FLO)  return corvus_bool(a.f == b.f);
    if (a.type == VAL_STR)  return corvus_bool(strcmp(a.s, b.s) == 0);
    return corvus_bool(false);
}

static inline CorvusVal corvus_neq(CorvusVal a, CorvusVal b) {
    CorvusVal eq = corvus_eq(a, b);
    return corvus_bool(!eq.b);
}

static inline CorvusVal corvus_lt(CorvusVal a, CorvusVal b) {
    if (a.type == VAL_INT && b.type == VAL_INT) return corvus_bool(a.i < b.i);
    double da = (a.type == VAL_FLO) ? a.f : (double)a.i;
    double db = (b.type == VAL_FLO) ? b.f : (double)b.i;
    return corvus_bool(da < db);
}

static inline CorvusVal corvus_lte(CorvusVal a, CorvusVal b) {
    if (a.type == VAL_INT && b.type == VAL_INT) return corvus_bool(a.i <= b.i);
    double da = (a.type == VAL_FLO) ? a.f : (double)a.i;
    double db = (b.type == VAL_FLO) ? b.f : (double)b.i;
    return corvus_bool(da <= db);
}

static inline CorvusVal corvus_gt(CorvusVal a, CorvusVal b) {
    return corvus_lt(b, a);
}

static inline CorvusVal corvus_gte(CorvusVal a, CorvusVal b) {
    return corvus_lte(b, a);
}

static inline CorvusVal corvus_len(CorvusVal v) {
    if (v.type == VAL_STR) return corvus_int(strlen(v.s));
    if (v.type == VAL_LIST) return corvus_int(v.l.length);
    return corvus_int(0);
}

static inline CorvusVal corvus_index(CorvusVal target, CorvusVal idx) {
    if (target.type == VAL_LIST) {
        long long i = idx.i;
        if (i < 0) i += target.l.length;
        if (i < 0 || (size_t)i >= target.l.length) {
            fprintf(stderr, "[Corvus Panic]: List index out of range.\\n");
            exit(1);
        }
        return target.l.items[i];
    }
    return corvus_null();
}

static inline CorvusVal corvus_make_list(CorvusVal* items, size_t count) {
    CorvusVal v;
    v.type = VAL_LIST;
    v.l.length = count;
    v.l.capacity = count;
    v.l.items = (CorvusVal*)malloc(sizeof(CorvusVal) * (count > 0 ? count : 1));
    if (items && count > 0) {
        memcpy(v.l.items, items, sizeof(CorvusVal) * count);
    }
    return v;
}
"""

class CTranspiler:
    def __init__(self):
        self.func_declarations = []
        self.func_implementations = []
        self.declared_vars = set()
        self.declared_functions = set()
        self.lambda_count = 0

    def transpile(self, ast: ProgramNode) -> str:
        main_lines = []
        for stmt in ast.statements:
            line = self.transpile_statement(stmt)
            if line:
                main_lines.append(line)

        output = []
        output.append(C_RUNTIME_HEADER)
        output.append("\n/* Function Declarations */")
        output.extend(self.func_declarations)
        output.append("\n/* Function Implementations */")
        output.extend(self.func_implementations)
        output.append("\nint main(int argc, char** argv) {")
        for line in main_lines:
            output.append(f"    {line}")
        output.append("    return 0;")
        output.append("}\n")
        return "\n".join(output)

    def transpile_statement(self, stmt) -> str:
        if isinstance(stmt, VarDeclNode):
            val_code = self.transpile_expr(stmt.value) if stmt.value else "corvus_null()"
            self.declared_vars.add(stmt.name)
            return f"CorvusVal {stmt.name} = {val_code};"

        elif isinstance(stmt, ConstDeclNode):
            val_code = self.transpile_expr(stmt.value)
            self.declared_vars.add(stmt.name)
            return f"const CorvusVal {stmt.name} = {val_code};"

        elif isinstance(stmt, AssignmentNode):
            val_code = self.transpile_expr(stmt.value)
            return f"{stmt.target} = {val_code};"

        elif isinstance(stmt, FuncCallNode):
            return f"{self.transpile_expr(stmt)};"

        elif isinstance(stmt, MethodCallNode):
            return f"{self.transpile_expr(stmt)};"

        elif isinstance(stmt, GivoutNode):
            val_code = self.transpile_expr(stmt.value) if stmt.value else "corvus_null()"
            return f"return {val_code};"

        elif isinstance(stmt, BreakNode):
            return "break;"

        elif isinstance(stmt, ContinueNode):
            return "continue;"

        elif isinstance(stmt, PassNode):
            return "; /* pass */"

        elif isinstance(stmt, GetNode):
            return f"/* get {stmt.module_name} */"

        elif isinstance(stmt, IfNode):
            lines = []
            cond_code = self.transpile_expr(stmt.condition)
            lines.append(f"if (corvus_is_true({cond_code})) {{")
            for s in stmt.then_block.statements:
                lines.append(f"    {self.transpile_statement(s)}")
            for el_cond, el_body in stmt.elsif_branches:
                el_c = self.transpile_expr(el_cond)
                lines.append(f"}} else if (corvus_is_true({el_c})) {{")
                for s in el_body.statements:
                    lines.append(f"    {self.transpile_statement(s)}")
            if stmt.else_block:
                lines.append("} else {")
                for s in stmt.else_block.statements:
                    lines.append(f"    {self.transpile_statement(s)}")
            lines.append("}")
            return "\n    ".join(lines)

        elif isinstance(stmt, WhileNode):
            lines = []
            cond_code = self.transpile_expr(stmt.condition)
            lines.append(f"while (corvus_is_true({cond_code})) {{")
            for s in stmt.body.statements:
                lines.append(f"    {self.transpile_statement(s)}")
            lines.append("}")
            return "\n    ".join(lines)

        elif isinstance(stmt, FuncDeclNode):
            self.declared_functions.add(stmt.name)
            params_decl = ", ".join(f"CorvusVal {p}" for p in stmt.params)
            self.func_declarations.append(f"CorvusVal {stmt.name}({params_decl});")
            fn_lines = [f"CorvusVal {stmt.name}({params_decl}) {{"]
            for s in stmt.body.statements:
                fn_lines.append(f"    {self.transpile_statement(s)}")
            fn_lines.append("    return corvus_null();")
            fn_lines.append("}\n")
            self.func_implementations.append("\n".join(fn_lines))
            return ""

        return f"/* {type(stmt).__name__} */"

    def transpile_expr(self, expr) -> str:
        if isinstance(expr, LiteralNode):
            val = expr.value
            if val is None: return "corvus_null()"
            if isinstance(val, bool): return f"corvus_bool({'true' if val else 'false'})"
            if isinstance(val, int): return f"corvus_int({val}LL)"
            if isinstance(val, float): return f"corvus_flo({val})"
            if isinstance(val, str):
                escaped = val.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n')
                return f'corvus_str("{escaped}")'

        elif isinstance(expr, IdentifierNode):
            return expr.name

        elif isinstance(expr, LambdaNode):
            self.lambda_count += 1
            lmb_name = f"_crv_lmb_{self.lambda_count}"
            params_decl = ", ".join(f"CorvusVal {p}" for p in expr.params)
            self.func_declarations.append(f"CorvusVal {lmb_name}({params_decl});")
            if isinstance(expr.body, BlockNode):
                body_code = "\n".join(f"    {self.transpile_statement(s)}" for s in expr.body.statements)
            else:
                body_code = f"    return {self.transpile_expr(expr.body)};"
            lmb_impl = f"CorvusVal {lmb_name}({params_decl}) {{\n{body_code}\n    return corvus_null();\n}}\n"
            self.func_implementations.append(lmb_impl)
            return f"corvus_func((CorvusFnPtr){lmb_name})"

        elif isinstance(expr, BinOpNode):
            l = self.transpile_expr(expr.left)
            r = self.transpile_expr(expr.right)
            op = expr.op
            if op == '+':  return f"corvus_add({l}, {r})"
            if op == '-':  return f"corvus_sub({l}, {r})"
            if op == '*':  return f"corvus_mul({l}, {r})"
            if op == '/':  return f"corvus_div({l}, {r})"
            if op == '%':  return f"corvus_mod({l}, {r})"
            if op == '**': return f"corvus_pow({l}, {r})"
            if op == '==': return f"corvus_eq({l}, {r})"
            if op == '!=': return f"corvus_neq({l}, {r})"
            if op == '<':  return f"corvus_lt({l}, {r})"
            if op == '<=': return f"corvus_lte({l}, {r})"
            if op == '>':  return f"corvus_gt({l}, {r})"
            if op == '>=': return f"corvus_gte({l}, {r})"
            if op == 'and': return f"corvus_bool(corvus_is_true({l}) && corvus_is_true({r}))"
            if op == 'or':  return f"corvus_bool(corvus_is_true({l}) || corvus_is_true({r}))"
            if op == 'xor': return f"corvus_bool(corvus_is_true({l}) ^ corvus_is_true({r}))"

        elif isinstance(expr, UnaryOpNode):
            opnd = self.transpile_expr(expr.operand)
            if expr.op == '-': return f"corvus_sub(corvus_int(0), {opnd})"
            if expr.op == 'not': return f"corvus_bool(!corvus_is_true({opnd}))"

        elif isinstance(expr, TernaryNode):
            c = self.transpile_expr(expr.condition)
            t = self.transpile_expr(expr.true_expr)
            f = self.transpile_expr(expr.false_expr)
            return f"(corvus_is_true({c}) ? {t} : {f})"

        elif isinstance(expr, FStringNode):
            parts = [self.transpile_expr(p) for p in expr.parts]
            if not parts: return 'corvus_str("")'
            res = parts[0]
            for p in parts[1:]:
                res = f"corvus_add({res}, {p})"
            return res

        elif isinstance(expr, IndexAccessNode):
            t = self.transpile_expr(expr.target)
            i = self.transpile_expr(expr.index)
            return f"corvus_index({t}, {i})"

        elif isinstance(expr, MethodCallNode):
            t = self.transpile_expr(expr.target)
            if expr.method_name in ('len', 'length'):
                return f"corvus_len({t})"
            return f"/* method {expr.method_name} */ corvus_null()"

        elif isinstance(expr, FuncCallNode):
            callee_name = expr.callee.name if isinstance(expr.callee, IdentifierNode) else None
            args_code = [self.transpile_expr(a) for a in expr.args]
            if callee_name in ('log', 'print'):
                calls = []
                for a in args_code:
                    calls.append(f'corvus_print_val({a}); printf(" ");')
                calls.append('printf("\\n");')
                return " ".join(calls)
            elif callee_name == 'len':
                return f"corvus_len({args_code[0]})"
            elif callee_name == 'str':
                return args_code[0]
            elif callee_name == 'int':
                return args_code[0]
            elif callee_name in self.declared_functions:
                return f"{callee_name}({', '.join(args_code)})"
            elif callee_name:
                # Could be a variable holding a function pointer / lambda
                param_types = ", ".join(["CorvusVal"] * len(args_code))
                fn_sig = f"CorvusVal (*)({param_types})"
                return f"(({fn_sig})({callee_name}.fn))({', '.join(args_code)})"

        elif isinstance(expr, ListNode):
            elements = [self.transpile_expr(e) for e in expr.elements]
            n = len(elements)
            if n == 0:
                return "corvus_make_list(NULL, 0)"
            return f"corvus_make_list((CorvusVal[]){{{', '.join(elements)}}}, {n})"

        return "corvus_null()"
