# Corvus to C99 High-Performance Transpiler Backend (Full Feature Parity v4.4)
# Emits optimized ISO C99 code ready for GCC/Clang/MSVC compilation with -O3

import os
import sys

from Compiler_Core.astnodes import (
    ProgramNode, LiteralNode, IdentifierNode, ListNode, TupleNode, DictNode,
    BinOpNode, UnaryOpNode, SafeNavNode, IndexAccessNode, MethodCallNode,
    VarDeclNode, ConstDeclNode, AssignmentNode, BlockNode, IfNode, WhileNode,
    ForNode, BreakNode, ContinueNode, PassNode, GivoutNode, FuncDeclNode,
    LambdaNode, FuncCallNode, ClassDeclNode, GlobalNode, GetNode, AwaitNode,
    TryErrorNode, InputNode, PipelineNode, MatchNode, CaseNode, TernaryNode, FStringNode
)

C_RUNTIME_HEADER = """/* Generated by Corvus C99 Transpiler Engine v4.4.0 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include <math.h>
#include <ctype.h>
#include <time.h>

#if defined(_WIN32) || defined(_WIN64)
#include <windows.h>
#else
#include <unistd.h>
#endif

typedef enum {
    VAL_NULL,
    VAL_BOOL,
    VAL_INT,
    VAL_FLO,
    VAL_STR,
    VAL_LIST,
    VAL_DICT,
    VAL_FUNC
} ValType;

struct CorvusVal;

typedef struct CorvusList {
    struct CorvusVal* items;
    size_t length;
    size_t capacity;
} CorvusList;

typedef struct CorvusDict {
    char** keys;
    struct CorvusVal* vals;
    size_t length;
    size_t capacity;
} CorvusDict;

typedef struct CorvusVal (*CorvusFnPtr)();

typedef struct CorvusVal {
    ValType type;
    union {
        bool b;
        long long i;
        double f;
        char* s;
        CorvusList l;
        CorvusDict d;
        CorvusFnPtr fn;
    };
} CorvusVal;

static inline CorvusVal corvus_null(void) {
    CorvusVal v; v.type = VAL_NULL; v.i = 0; return v;
}

static inline CorvusVal corvus_bool(bool b) {
    CorvusVal v; v.type = VAL_BOOL; v.b = b; return v;
}

static inline CorvusVal corvus_int(long long i) {
    CorvusVal v; v.type = VAL_INT; v.i = i; return v;
}

static inline CorvusVal corvus_flo(double f) {
    CorvusVal v; v.type = VAL_FLO; v.f = f; return v;
}

static inline CorvusVal corvus_str(const char* s) {
    CorvusVal v; v.type = VAL_STR;
    if (!s) { v.s = strdup(""); }
    else { v.s = strdup(s); }
    return v;
}

static inline CorvusVal corvus_func(CorvusFnPtr fn) {
    CorvusVal v; v.type = VAL_FUNC; v.fn = fn; return v;
}

static inline bool corvus_is_true(CorvusVal v) {
    switch (v.type) {
        case VAL_NULL: return false;
        case VAL_BOOL: return v.b;
        case VAL_INT:  return v.i != 0;
        case VAL_FLO:  return v.f != 0.0;
        case VAL_STR:  return v.s && strlen(v.s) > 0;
        case VAL_LIST: return v.l.length > 0;
        case VAL_DICT: return v.d.length > 0;
        case VAL_FUNC: return true;
        default: return false;
    }
}

static void corvus_print_val(CorvusVal v);

static inline void corvus_print_dict(CorvusDict d) {
    printf("{");
    for (size_t k = 0; k < d.length; k++) {
        printf("'%s': ", d.keys[k]);
        if (d.vals[k].type == VAL_STR) {
            printf("'%s'", d.vals[k].s);
        } else {
            corvus_print_val(d.vals[k]);
        }
        if (k + 1 < d.length) printf(", ");
    }
    printf("}");
}

static void corvus_print_val(CorvusVal v) {
    switch (v.type) {
        case VAL_NULL: printf("null"); break;
        case VAL_BOOL: printf("%s", v.b ? "true" : "false"); break;
        case VAL_INT:  printf("%lld", v.i); break;
        case VAL_FLO:  printf("%g", v.f); break;
        case VAL_STR:  printf("%s", v.s ? v.s : ""); break;
        case VAL_FUNC: printf("<function>"); break;
        case VAL_LIST: {
            printf("[");
            for (size_t k = 0; k < v.l.length; k++) {
                if (v.l.items[k].type == VAL_STR) {
                    printf("'%s'", v.l.items[k].s);
                } else {
                    corvus_print_val(v.l.items[k]);
                }
                if (k + 1 < v.l.length) printf(", ");
            }
            printf("]");
            break;
        }
        case VAL_DICT: {
            corvus_print_dict(v.d);
            break;
        }
    }
}

static inline CorvusVal corvus_add(CorvusVal a, CorvusVal b) {
    if (a.type == VAL_INT && b.type == VAL_INT) return corvus_int(a.i + b.i);
    if ((a.type == VAL_INT || a.type == VAL_FLO) && (b.type == VAL_INT || b.type == VAL_FLO)) {
        double da = (a.type == VAL_FLO) ? a.f : (double)a.i;
        double db = (b.type == VAL_FLO) ? b.f : (double)b.i;
        return corvus_flo(da + db);
    }
    if (a.type == VAL_STR || b.type == VAL_STR) {
        char buf1[64], buf2[64];
        const char *s1 = (a.type == VAL_STR) ? a.s : (snprintf(buf1, 64, "%lld", a.i), buf1);
        const char *s2 = (b.type == VAL_STR) ? b.s : (snprintf(buf2, 64, "%lld", b.i), buf2);
        size_t len = strlen(s1) + strlen(s2) + 1;
        char* out = (char*)malloc(len);
        strcpy(out, s1);
        strcat(out, s2);
        CorvusVal v; v.type = VAL_STR; v.s = out;
        return v;
    }
    if (a.type == VAL_LIST && b.type == VAL_LIST) {
        size_t n = a.l.length + b.l.length;
        CorvusVal res; res.type = VAL_LIST; res.l.length = n; res.l.capacity = n;
        res.l.items = (CorvusVal*)malloc(sizeof(CorvusVal) * (n > 0 ? n : 1));
        memcpy(res.l.items, a.l.items, sizeof(CorvusVal) * a.l.length);
        memcpy(res.l.items + a.l.length, b.l.items, sizeof(CorvusVal) * b.l.length);
        return res;
    }
    return corvus_int(a.i + b.i);
}

static inline CorvusVal corvus_sub(CorvusVal a, CorvusVal b) {
    if (a.type == VAL_INT && b.type == VAL_INT) return corvus_int(a.i - b.i);
    double da = (a.type == VAL_FLO) ? a.f : (double)a.i;
    double db = (b.type == VAL_FLO) ? b.f : (double)b.i;
    return corvus_flo(da - db);
}

static inline CorvusVal corvus_mul(CorvusVal a, CorvusVal b) {
    if (a.type == VAL_INT && b.type == VAL_INT) return corvus_int(a.i * b.i);
    double da = (a.type == VAL_FLO) ? a.f : (double)a.i;
    double db = (b.type == VAL_FLO) ? b.f : (double)b.i;
    return corvus_flo(da * db);
}

static inline CorvusVal corvus_div(CorvusVal a, CorvusVal b) {
    double da = (a.type == VAL_FLO) ? a.f : (double)a.i;
    double db = (b.type == VAL_FLO) ? b.f : (double)b.i;
    if (db == 0.0) {
        fprintf(stderr, "[Corvus Panic]: Division by zero.\\n");
        exit(1);
    }
    if (a.type == VAL_INT && b.type == VAL_INT && (a.i % b.i == 0)) {
        return corvus_int(a.i / b.i);
    }
    return corvus_flo(da / db);
}

static inline CorvusVal corvus_mod(CorvusVal a, CorvusVal b) {
    if (b.i == 0) {
        fprintf(stderr, "[Corvus Panic]: Modulo by zero.\\n");
        exit(1);
    }
    return corvus_int(a.i % b.i);
}

static inline CorvusVal corvus_pow(CorvusVal a, CorvusVal b) {
    double da = (a.type == VAL_FLO) ? a.f : (double)a.i;
    double db = (b.type == VAL_FLO) ? b.f : (double)b.i;
    double res = pow(da, db);
    if (a.type == VAL_INT && b.type == VAL_INT && b.i >= 0) return corvus_int((long long)res);
    return corvus_flo(res);
}

static inline CorvusVal corvus_eq(CorvusVal a, CorvusVal b) {
    if (a.type != b.type) return corvus_bool(false);
    if (a.type == VAL_NULL) return corvus_bool(true);
    if (a.type == VAL_BOOL) return corvus_bool(a.b == b.b);
    if (a.type == VAL_INT)  return corvus_bool(a.i == b.i);
    if (a.type == VAL_FLO)  return corvus_bool(a.f == b.f);
    if (a.type == VAL_STR)  return corvus_bool(strcmp(a.s, b.s) == 0);
    return corvus_bool(false);
}

static inline CorvusVal corvus_neq(CorvusVal a, CorvusVal b) {
    CorvusVal eq = corvus_eq(a, b);
    return corvus_bool(!eq.b);
}

static inline CorvusVal corvus_lt(CorvusVal a, CorvusVal b) {
    if (a.type == VAL_INT && b.type == VAL_INT) return corvus_bool(a.i < b.i);
    double da = (a.type == VAL_FLO) ? a.f : (double)a.i;
    double db = (b.type == VAL_FLO) ? b.f : (double)b.i;
    return corvus_bool(da < db);
}

static inline CorvusVal corvus_lte(CorvusVal a, CorvusVal b) {
    if (a.type == VAL_INT && b.type == VAL_INT) return corvus_bool(a.i <= b.i);
    double da = (a.type == VAL_FLO) ? a.f : (double)a.i;
    double db = (b.type == VAL_FLO) ? b.f : (double)b.i;
    return corvus_bool(da <= db);
}

static inline CorvusVal corvus_gt(CorvusVal a, CorvusVal b) {
    return corvus_lt(b, a);
}

static inline CorvusVal corvus_gte(CorvusVal a, CorvusVal b) {
    return corvus_lte(b, a);
}

static inline CorvusVal corvus_len(CorvusVal v) {
    if (v.type == VAL_STR) return corvus_int(strlen(v.s));
    if (v.type == VAL_LIST) return corvus_int(v.l.length);
    if (v.type == VAL_DICT) return corvus_int(v.d.length);
    return corvus_int(0);
}

static inline CorvusVal corvus_make_list(CorvusVal* items, size_t count) {
    CorvusVal v;
    v.type = VAL_LIST;
    v.l.length = count;
    v.l.capacity = count > 4 ? count : 4;
    v.l.items = (CorvusVal*)malloc(sizeof(CorvusVal) * v.l.capacity);
    if (items && count > 0) {
        memcpy(v.l.items, items, sizeof(CorvusVal) * count);
    }
    return v;
}

static inline void corvus_list_add(CorvusVal* list, CorvusVal item) {
    if (list->type != VAL_LIST) return;
    if (list->l.length >= list->l.capacity) {
        list->l.capacity = (list->l.capacity == 0) ? 4 : list->l.capacity * 2;
        list->l.items = (CorvusVal*)realloc(list->l.items, sizeof(CorvusVal) * list->l.capacity);
    }
    list->l.items[list->l.length++] = item;
}

static inline CorvusVal corvus_list_pop(CorvusVal* list) {
    if (list->type != VAL_LIST || list->l.length == 0) return corvus_null();
    return list->l.items[--list->l.length];
}

static inline CorvusVal corvus_make_dict(const char** keys, CorvusVal* vals, size_t count) {
    CorvusVal v;
    v.type = VAL_DICT;
    v.d.length = count;
    v.d.capacity = count > 4 ? count : 4;
    v.d.keys = (char**)malloc(sizeof(char*) * v.d.capacity);
    v.d.vals = (CorvusVal*)malloc(sizeof(CorvusVal) * v.d.capacity);
    for (size_t k = 0; k < count; k++) {
        v.d.keys[k] = strdup(keys[k]);
        v.d.vals[k] = vals[k];
    }
    return v;
}

static inline CorvusVal corvus_dict_get(CorvusVal dict, CorvusVal key) {
    if (dict.type != VAL_DICT || key.type != VAL_STR) return corvus_null();
    for (size_t k = 0; k < dict.d.length; k++) {
        if (strcmp(dict.d.keys[k], key.s) == 0) {
            return dict.d.vals[k];
        }
    }
    return corvus_null();
}

static inline void corvus_dict_set(CorvusVal* dict, CorvusVal key, CorvusVal val) {
    if (dict->type != VAL_DICT || key.type != VAL_STR) return;
    for (size_t k = 0; k < dict->d.length; k++) {
        if (strcmp(dict->d.keys[k], key.s) == 0) {
            dict->d.vals[k] = val;
            return;
        }
    }
    if (dict->d.length >= dict->d.capacity) {
        dict->d.capacity = (dict->d.capacity == 0) ? 4 : dict->d.capacity * 2;
        dict->d.keys = (char**)realloc(dict->d.keys, sizeof(char*) * dict->d.capacity);
        dict->d.vals = (CorvusVal*)realloc(dict->d.vals, sizeof(CorvusVal) * dict->d.capacity);
    }
    dict->d.keys[dict->d.length] = strdup(key.s);
    dict->d.vals[dict->d.length] = val;
    dict->d.length++;
}

static inline CorvusVal corvus_index(CorvusVal target, CorvusVal idx) {
    if (target.type == VAL_LIST) {
        long long i = idx.i;
        if (i < 0) i += target.l.length;
        if (i < 0 || (size_t)i >= target.l.length) {
            fprintf(stderr, "[Corvus Panic]: List index out of range.\\n");
            exit(1);
        }
        return target.l.items[i];
    }
    if (target.type == VAL_DICT) {
        return corvus_dict_get(target, idx);
    }
    if (target.type == VAL_STR) {
        long long i = idx.i;
        size_t len = strlen(target.s);
        if (i < 0) i += len;
        if (i < 0 || (size_t)i >= len) return corvus_null();
        char buf[2];
        buf[0] = target.s[i];
        buf[1] = 0;
        return corvus_str(buf);
    }
    return corvus_null();
}

/* Native 2D Matrix Multiplication (@ Operator) */
static inline CorvusVal corvus_matmul(CorvusVal A, CorvusVal B) {
    if (A.type != VAL_LIST || B.type != VAL_LIST || A.l.length == 0 || B.l.length == 0) {
        fprintf(stderr, "[Corvus Panic]: Incompatible operands for matrix multiplication @.\\n");
        exit(1);
    }
    size_t rows_A = A.l.length;
    CorvusVal first_row_A = A.l.items[0];
    if (first_row_A.type != VAL_LIST) {
        fprintf(stderr, "[Corvus Panic]: Left operand of @ must be a 2D matrix.\\n");
        exit(1);
    }
    size_t cols_A = first_row_A.l.length;
    size_t rows_B = B.l.length;
    CorvusVal first_row_B = B.l.items[0];
    if (first_row_B.type != VAL_LIST) {
        fprintf(stderr, "[Corvus Panic]: Right operand of @ must be a 2D matrix.\\n");
        exit(1);
    }
    size_t cols_B = first_row_B.l.length;
    if (cols_A != rows_B) {
        fprintf(stderr, "[Corvus Panic]: Dimension mismatch for @: %zu != %zu\\n", cols_A, rows_B);
        exit(1);
    }

    CorvusVal result = corvus_make_list(NULL, 0);
    for (size_t r = 0; r < rows_A; r++) {
        CorvusVal row_out = corvus_make_list(NULL, 0);
        CorvusVal row_a = A.l.items[r];
        for (size_t c = 0; c < cols_B; c++) {
            double dot = 0.0;
            bool is_all_int = true;
            for (size_t k = 0; k < cols_A; k++) {
                CorvusVal el_a = row_a.l.items[k];
                CorvusVal el_b = B.l.items[k].l.items[c];
                double va = (el_a.type == VAL_FLO) ? el_a.f : (double)el_a.i;
                double vb = (el_b.type == VAL_FLO) ? el_b.f : (double)el_b.i;
                if (el_a.type == VAL_FLO || el_b.type == VAL_FLO) is_all_int = false;
                dot += va * vb;
            }
            if (is_all_int) {
                corvus_list_add(&row_out, corvus_int((long long)dot));
            } else {
                corvus_list_add(&row_out, corvus_flo(dot));
            }
        }
        corvus_list_add(&result, row_out);
    }
    return result;
}

/* Built-in Library Functions */
static inline CorvusVal corvus_sum(CorvusVal lis) {
    if (lis.type != VAL_LIST) return corvus_int(0);
    double total = 0.0;
    bool is_flo = false;
    for (size_t k = 0; k < lis.l.length; k++) {
        CorvusVal it = lis.l.items[k];
        if (it.type == VAL_FLO) { is_flo = true; total += it.f; }
        else if (it.type == VAL_INT) { total += (double)it.i; }
    }
    return is_flo ? corvus_flo(total) : corvus_int((long long)total);
}

static inline CorvusVal corvus_min(CorvusVal a, CorvusVal b) {
    return corvus_is_true(corvus_lt(a, b)) ? a : b;
}

static inline CorvusVal corvus_max(CorvusVal a, CorvusVal b) {
    return corvus_is_true(corvus_gt(a, b)) ? a : b;
}

static inline CorvusVal corvus_abs(CorvusVal v) {
    if (v.type == VAL_INT) return corvus_int(v.i < 0 ? -v.i : v.i);
    if (v.type == VAL_FLO) return corvus_flo(fabs(v.f));
    return v;
}

static inline CorvusVal corvus_round(CorvusVal v, CorvusVal decimals) {
    double factor = pow(10.0, (double)decimals.i);
    double val = (v.type == VAL_FLO) ? v.f : (double)v.i;
    double rounded = round(val * factor) / factor;
    return (decimals.i == 0) ? corvus_int((long long)rounded) : corvus_flo(rounded);
}

static inline CorvusVal corvus_type_fn(CorvusVal v) {
    switch (v.type) {
        case VAL_NULL: return corvus_str("null");
        case VAL_BOOL: return corvus_str("bool");
        case VAL_INT:  return corvus_str("int");
        case VAL_FLO:  return corvus_str("flo");
        case VAL_STR:  return corvus_str("str");
        case VAL_LIST: return corvus_str("lis");
        case VAL_DICT: return corvus_str("dic");
        case VAL_FUNC: return corvus_str("func");
        default:       return corvus_str("any");
    }
}

static inline CorvusVal corvus_range(CorvusVal start, CorvusVal stop, CorvusVal step) {
    CorvusVal res = corvus_make_list(NULL, 0);
    long long st = start.i;
    long long sp = stop.i;
    long long inc = step.i == 0 ? 1 : step.i;
    if (inc > 0) {
        for (long long cur = st; cur < sp; cur += inc) {
            corvus_list_add(&res, corvus_int(cur));
        }
    } else {
        for (long long cur = st; cur > sp; cur += inc) {
            corvus_list_add(&res, corvus_int(cur));
        }
    }
    return res;
}

static inline CorvusVal corvus_str_upper(CorvusVal s) {
    if (s.type != VAL_STR) return s;
    char* copy = strdup(s.s);
    for (size_t k = 0; copy[k]; k++) copy[k] = (char)toupper((unsigned char)copy[k]);
    CorvusVal out; out.type = VAL_STR; out.s = copy;
    return out;
}

static inline CorvusVal corvus_str_lower(CorvusVal s) {
    if (s.type != VAL_STR) return s;
    char* copy = strdup(s.s);
    for (size_t k = 0; copy[k]; k++) copy[k] = (char)tolower((unsigned char)copy[k]);
    CorvusVal out; out.type = VAL_STR; out.s = copy;
    return out;
}

static inline CorvusVal corvus_str_trim(CorvusVal s) {
    if (s.type != VAL_STR) return s;
    const char* start = s.s;
    while (*start && isspace((unsigned char)*start)) start++;
    const char* end = s.s + strlen(s.s) - 1;
    while (end > start && isspace((unsigned char)*end)) end--;
    size_t len = (end >= start) ? (size_t)(end - start + 1) : 0;
    char* buf = (char*)malloc(len + 1);
    if (len > 0) memcpy(buf, start, len);
    buf[len] = 0;
    CorvusVal out; out.type = VAL_STR; out.s = buf;
    return out;
}

/* Standard Modules Emulation in C */
static inline CorvusVal corvus_math_sqrt(CorvusVal v) {
    double d = (v.type == VAL_FLO) ? v.f : (double)v.i;
    return corvus_flo(sqrt(d));
}

static inline CorvusVal corvus_math_sin(CorvusVal v) {
    double d = (v.type == VAL_FLO) ? v.f : (double)v.i;
    return corvus_flo(sin(d));
}

static inline CorvusVal corvus_math_cos(CorvusVal v) {
    double d = (v.type == VAL_FLO) ? v.f : (double)v.i;
    return corvus_flo(cos(d));
}

static inline CorvusVal corvus_chrono_now(void) {
    time_t t = time(NULL);
    return corvus_flo((double)t);
}

static inline CorvusVal corvus_chrono_sleep(CorvusVal ms) {
#if defined(_WIN32) || defined(_WIN64)
    Sleep((DWORD)ms.i);
#else
    usleep((useconds_t)(ms.i * 1000));
#endif
    return corvus_null();
}

static inline CorvusVal corvus_process_platform(void) {
#if defined(_WIN32) || defined(_WIN64)
    return corvus_str("win32");
#elif defined(__APPLE__)
    return corvus_str("darwin");
#else
    return corvus_str("linux");
#endif
}
"""

class CTranspiler:
    def __init__(self):
        self.func_declarations = []
        self.func_implementations = []
        self.declared_vars = set()
        self.declared_functions = set()
        self.lambda_count = 0

    def transpile(self, ast: ProgramNode) -> str:
        main_lines = []
        for stmt in ast.statements:
            line = self.transpile_statement(stmt)
            if line:
                main_lines.append(line)

        output = [C_RUNTIME_HEADER]
        if self.func_declarations:
            output.append("/* Function Declarations */")
            output.extend(self.func_declarations)
            output.append("")

        if self.func_implementations:
            output.append("/* Function Implementations */")
            output.extend(self.func_implementations)
            output.append("")

        output.append("/* Main Program Entry */")
        output.append("int main(int argc, char* argv[]) {")
        for line in main_lines:
            output.append(f"    {line}")
        output.append("    return 0;")
        output.append("}\n")
        return "\n".join(output)

    def transpile_statement(self, stmt) -> str:
        if isinstance(stmt, VarDeclNode):
            val_code = self.transpile_expr(stmt.value) if stmt.value else "corvus_null()"
            self.declared_vars.add(stmt.name)
            return f"CorvusVal {stmt.name} = {val_code};"

        elif isinstance(stmt, ConstDeclNode):
            val_code = self.transpile_expr(stmt.value)
            self.declared_vars.add(stmt.name)
            return f"const CorvusVal {stmt.name} = {val_code};"

        elif isinstance(stmt, AssignmentNode):
            val_code = self.transpile_expr(stmt.value)
            if isinstance(stmt.target, IndexAccessNode):
                tgt = self.transpile_expr(stmt.target.target)
                idx = self.transpile_expr(stmt.target.index)
                return f"if ({tgt}.type == VAL_DICT) corvus_dict_set(&{tgt}, {idx}, {val_code}); else if ({tgt}.type == VAL_LIST) {tgt}.l.items[{idx}.i] = {val_code};"
            target_name = stmt.target.name if isinstance(stmt.target, IdentifierNode) else str(stmt.target)
            return f"{target_name} = {val_code};"

        elif isinstance(stmt, FuncCallNode):
            return f"{self.transpile_expr(stmt)};"

        elif isinstance(stmt, MethodCallNode):
            t_code = self.transpile_expr(stmt.target)
            if stmt.method_name in ('add', 'append', 'push') and stmt.args:
                arg_code = self.transpile_expr(stmt.args[0])
                return f"corvus_list_add(&{t_code}, {arg_code});"
            return f"{self.transpile_expr(stmt)};"

        elif isinstance(stmt, GivoutNode):
            val_code = self.transpile_expr(stmt.value) if stmt.value else "corvus_null()"
            return f"return {val_code};"

        elif isinstance(stmt, BreakNode):
            return "break;"

        elif isinstance(stmt, ContinueNode):
            return "continue;"

        elif isinstance(stmt, PassNode):
            return "; /* pass */"

        elif isinstance(stmt, GetNode):
            return f"/* get {stmt.module_name} */"

        elif isinstance(stmt, IfNode):
            lines = []
            cond_code = self.transpile_expr(stmt.condition)
            lines.append(f"if (corvus_is_true({cond_code})) {{")
            for s in stmt.then_block.statements:
                lines.append(f"    {self.transpile_statement(s)}")
            for el_cond, el_body in stmt.elsif_branches:
                el_c = self.transpile_expr(el_cond)
                lines.append(f"}} else if (corvus_is_true({el_c})) {{")
                for s in el_body.statements:
                    lines.append(f"    {self.transpile_statement(s)}")
            if stmt.else_block:
                lines.append("} else {")
                for s in stmt.else_block.statements:
                    lines.append(f"    {self.transpile_statement(s)}")
            lines.append("}")
            return "\n    ".join(lines)

        elif isinstance(stmt, WhileNode):
            lines = []
            cond_code = self.transpile_expr(stmt.condition)
            lines.append(f"while (corvus_is_true({cond_code})) {{")
            for s in stmt.body.statements:
                lines.append(f"    {self.transpile_statement(s)}")
            lines.append("}")
            return "\n    ".join(lines)

        elif isinstance(stmt, ForNode):
            lines = []
            col_code = self.transpile_expr(stmt.collection)
            iter_var = stmt.iterator
            lines.append(f"{{ CorvusVal _col = {col_code};")
            lines.append(f"  for (size_t _idx = 0; _idx < _col.l.length; _idx++) {{")
            lines.append(f"    CorvusVal {iter_var} = _col.l.items[_idx];")
            for s in stmt.body.statements:
                lines.append(f"    {self.transpile_statement(s)}")
            lines.append("  }")
            lines.append("}")
            return "\n    ".join(lines)

        elif isinstance(stmt, FuncDeclNode):
            self.declared_functions.add(stmt.name)
            params_decl = ", ".join(f"CorvusVal {p}" for p in stmt.params)
            self.func_declarations.append(f"CorvusVal {stmt.name}({params_decl});")
            fn_lines = [f"CorvusVal {stmt.name}({params_decl}) {{"]
            for s in stmt.body.statements:
                fn_lines.append(f"    {self.transpile_statement(s)}")
            fn_lines.append("    return corvus_null();")
            fn_lines.append("}\n")
            self.func_implementations.append("\n".join(fn_lines))
            return ""

        elif isinstance(stmt, MatchNode):
            lines = []
            tgt_code = self.transpile_expr(stmt.target)
            lines.append(f"{{ CorvusVal _m_tgt = {tgt_code}; bool _m_matched = false;")
            for idx, case in enumerate(stmt.cases):
                p_code = self.transpile_expr(case.pattern)
                prefix = "if" if idx == 0 else "else if"
                lines.append(f"  {prefix} (!_m_matched && corvus_is_true(corvus_eq(_m_tgt, {p_code}))) {{")
                lines.append("    _m_matched = true;")
                if isinstance(case.body, BlockNode):
                    for s in case.body.statements:
                        lines.append(f"    {self.transpile_statement(s)}")
                else:
                    lines.append(f"    {self.transpile_statement(case.body)}")
                lines.append("  }")
            if stmt.default_branch:
                lines.append("  if (!_m_matched) {")
                if isinstance(stmt.default_branch, BlockNode):
                    for s in stmt.default_branch.statements:
                        lines.append(f"    {self.transpile_statement(s)}")
                else:
                    lines.append(f"    {self.transpile_statement(stmt.default_branch)}")
                lines.append("  }")
            lines.append("}")
            return "\n    ".join(lines)

        elif isinstance(stmt, TryErrorNode):
            lines = []
            for s in stmt.try_block.statements:
                lines.append(self.transpile_statement(s))
            if stmt.final_block:
                for s in stmt.final_block.statements:
                    lines.append(self.transpile_statement(s))
            return "\n    ".join(lines)

        elif isinstance(stmt, PipelineNode):
            return f"{self.transpile_expr(stmt)};"

        elif isinstance(stmt, BlockNode):
            lines = ["{"]
            for s in stmt.statements:
                lines.append(f"    {self.transpile_statement(s)}")
            lines.append("}")
            return "\n    ".join(lines)

        return f"/* {type(stmt).__name__} */"

    def transpile_expr(self, expr) -> str:
        if isinstance(expr, LiteralNode):
            val = expr.value
            if val is None: return "corvus_null()"
            if isinstance(val, bool): return f"corvus_bool({'true' if val else 'false'})"
            if isinstance(val, int): return f"corvus_int({val}LL)"
            if isinstance(val, float): return f"corvus_flo({val})"
            if isinstance(val, str):
                escaped = val.replace('\\', '\\\\').replace('"', '\\"').replace('\n', '\\n')
                return f'corvus_str("{escaped}")'

        elif isinstance(expr, IdentifierNode):
            if expr.name == "tru": return "corvus_bool(true)"
            if expr.name == "fal": return "corvus_bool(false)"
            if expr.name == "null": return "corvus_null()"
            return expr.name

        elif isinstance(expr, LambdaNode):
            self.lambda_count += 1
            lmb_name = f"_crv_lmb_{self.lambda_count}"
            params_decl = ", ".join(f"CorvusVal {p}" for p in expr.params)
            self.func_declarations.append(f"CorvusVal {lmb_name}({params_decl});")
            if isinstance(expr.body, BlockNode):
                body_code = "\n".join(f"    {self.transpile_statement(s)}" for s in expr.body.statements)
            else:
                body_code = f"    return {self.transpile_expr(expr.body)};"
            lmb_impl = f"CorvusVal {lmb_name}({params_decl}) {{\n{body_code}\n    return corvus_null();\n}}\n"
            self.func_implementations.append(lmb_impl)
            return f"corvus_func((CorvusFnPtr){lmb_name})"

        elif isinstance(expr, BinOpNode):
            l = self.transpile_expr(expr.left)
            r = self.transpile_expr(expr.right)
            op = expr.op
            if op == '+':  return f"corvus_add({l}, {r})"
            if op == '-':  return f"corvus_sub({l}, {r})"
            if op == '*':  return f"corvus_mul({l}, {r})"
            if op == '/':  return f"corvus_div({l}, {r})"
            if op == '%':  return f"corvus_mod({l}, {r})"
            if op == '**': return f"corvus_pow({l}, {r})"
            if op == '@':  return f"corvus_matmul({l}, {r})"
            if op == '==': return f"corvus_eq({l}, {r})"
            if op == '!=': return f"corvus_neq({l}, {r})"
            if op == '<':  return f"corvus_lt({l}, {r})"
            if op == '<=': return f"corvus_lte({l}, {r})"
            if op == '>':  return f"corvus_gt({l}, {r})"
            if op == '>=': return f"corvus_gte({l}, {r})"
            if op == 'and': return f"corvus_bool(corvus_is_true({l}) && corvus_is_true({r}))"
            if op == 'or':  return f"corvus_bool(corvus_is_true({l}) || corvus_is_true({r}))"
            if op == 'xor': return f"corvus_bool(corvus_is_true({l}) ^ corvus_is_true({r}))"

        elif isinstance(expr, UnaryOpNode):
            opnd = self.transpile_expr(expr.operand)
            if expr.op == '-': return f"corvus_sub(corvus_int(0), {opnd})"
            if expr.op == 'not': return f"corvus_bool(!corvus_is_true({opnd}))"

        elif isinstance(expr, TernaryNode):
            c = self.transpile_expr(expr.condition)
            t = self.transpile_expr(expr.true_expr)
            f = self.transpile_expr(expr.false_expr)
            return f"(corvus_is_true({c}) ? {t} : {f})"

        elif isinstance(expr, FStringNode):
            parts = [self.transpile_expr(p) for p in expr.parts]
            if not parts: return 'corvus_str("")'
            res = parts[0]
            for p in parts[1:]:
                res = f"corvus_add({res}, {p})"
            return res

        elif isinstance(expr, IndexAccessNode):
            t = self.transpile_expr(expr.target)
            i = self.transpile_expr(expr.index)
            return f"corvus_index({t}, {i})"

        elif isinstance(expr, MethodCallNode):
            t = self.transpile_expr(expr.target)
            m = expr.method_name
            target_name = getattr(expr.target, 'name', '')
            if m in ('len', 'length'):
                return f"corvus_len({t})"
            elif m in ('add', 'append', 'push') and expr.args:
                arg = self.transpile_expr(expr.args[0])
                return f"(corvus_list_add(&{t}, {arg}), corvus_null())"
            elif m == 'pop':
                return f"corvus_list_pop(&{t})"
            elif m == 'upper':
                return f"corvus_str_upper({t})"
            elif m == 'lower':
                return f"corvus_str_lower({t})"
            elif m == 'trim':
                return f"corvus_str_trim({t})"
            elif target_name == 'math':
                if m == 'sqrt' and expr.args: return f"corvus_math_sqrt({self.transpile_expr(expr.args[0])})"
                if m == 'sin' and expr.args: return f"corvus_math_sin({self.transpile_expr(expr.args[0])})"
                if m == 'cos' and expr.args: return f"corvus_math_cos({self.transpile_expr(expr.args[0])})"
            elif target_name == 'chrono':
                if m == 'now': return "corvus_chrono_now()"
                if m == 'sleep' and expr.args: return f"corvus_chrono_sleep({self.transpile_expr(expr.args[0])})"
            elif target_name == 'process':
                if m == 'get_platform': return "corvus_process_platform()"
            return f"/* method {m} */ corvus_null()"

        elif isinstance(expr, FuncCallNode):
            callee_name = expr.callee.name if isinstance(expr.callee, IdentifierNode) else None
            args_code = [self.transpile_expr(a) for a in expr.args]
            if callee_name in ('log', 'print'):
                calls = []
                for a in args_code:
                    calls.append(f'corvus_print_val({a}); printf(" ");')
                calls.append('printf("\\n");')
                return " ".join(calls)
            elif callee_name == 'len':
                return f"corvus_len({args_code[0]})"
            elif callee_name == 'sum' and args_code:
                return f"corvus_sum({args_code[0]})"
            elif callee_name == 'min' and len(args_code) >= 2:
                return f"corvus_min({args_code[0]}, {args_code[1]})"
            elif callee_name == 'max' and len(args_code) >= 2:
                return f"corvus_max({args_code[0]}, {args_code[1]})"
            elif callee_name == 'abs' and args_code:
                return f"corvus_abs({args_code[0]})"
            elif callee_name == 'round' and args_code:
                dec = args_code[1] if len(args_code) > 1 else "corvus_int(0)"
                return f"corvus_round({args_code[0]}, {dec})"
            elif callee_name == 'type' and args_code:
                return f"corvus_type_fn({args_code[0]})"
            elif callee_name == 'range' and args_code:
                st = "corvus_int(0)" if len(args_code) == 1 else args_code[0]
                sp = args_code[0] if len(args_code) == 1 else args_code[1]
                step = args_code[2] if len(args_code) > 2 else "corvus_int(1)"
                return f"corvus_range({st}, {sp}, {step})"
            elif callee_name == 'str' and args_code:
                return f"corvus_add(corvus_str(\"\"), {args_code[0]})"
            elif callee_name == 'int' and args_code:
                return args_code[0]
            elif callee_name in self.declared_functions:
                return f"{callee_name}({', '.join(args_code)})"
            elif callee_name:
                param_types = ", ".join(["CorvusVal"] * len(args_code))
                fn_sig = f"CorvusVal (*)({param_types})"
                return f"(({fn_sig})({callee_name}.fn))({', '.join(args_code)})"

        elif isinstance(expr, ListNode):
            elements = [self.transpile_expr(e) for e in expr.elements]
            n = len(elements)
            if n == 0:
                return "corvus_make_list(NULL, 0)"
            return f"corvus_make_list((CorvusVal[]){{{', '.join(elements)}}}, {n})"

        elif isinstance(expr, DictNode):
            k_list = []
            v_list = []
            for k_expr, v_expr in zip(expr.keys, expr.values):
                k_code = self.transpile_expr(k_expr)
                v_code = self.transpile_expr(v_expr)
                k_list.append(f"{k_code}.s")
                v_list.append(v_code)
            n = len(k_list)
            if n == 0:
                return "corvus_make_dict(NULL, NULL, 0)"
            return f"corvus_make_dict((const char*[]){{{', '.join(k_list)}}}, (CorvusVal[]){{{', '.join(v_list)}}}, {n})"

        elif isinstance(expr, PipelineNode):
            if isinstance(expr.right, FuncCallNode):
                expr.right.args.insert(0, expr.left)
                return self.transpile_expr(expr.right)
            elif isinstance(expr.right, IdentifierNode):
                return f"{expr.right.name}({self.transpile_expr(expr.left)})"

        return "corvus_null()"
