/* Generated by Corvus C99 Transpiler Engine v4.3.0 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include <math.h>
#include <ctype.h>
#include <time.h>

#if defined(_WIN32) || defined(_WIN64)
#include <windows.h>
#else
#include <unistd.h>
#endif

typedef enum {
    VAL_NULL,
    VAL_BOOL,
    VAL_INT,
    VAL_FLO,
    VAL_STR,
    VAL_LIST,
    VAL_DICT,
    VAL_FUNC
} ValType;

struct CorvusVal;

typedef struct CorvusList {
    struct CorvusVal* items;
    size_t length;
    size_t capacity;
} CorvusList;

typedef struct CorvusDict {
    char** keys;
    struct CorvusVal* vals;
    size_t length;
    size_t capacity;
} CorvusDict;

typedef struct CorvusVal (*CorvusFnPtr)();

typedef struct CorvusVal {
    ValType type;
    union {
        bool b;
        long long i;
        double f;
        char* s;
        CorvusList l;
        CorvusDict d;
        CorvusFnPtr fn;
    };
} CorvusVal;

static inline CorvusVal corvus_null(void) {
    CorvusVal v; v.type = VAL_NULL; v.i = 0; return v;
}

static inline CorvusVal corvus_bool(bool b) {
    CorvusVal v; v.type = VAL_BOOL; v.b = b; return v;
}

static inline CorvusVal corvus_int(long long i) {
    CorvusVal v; v.type = VAL_INT; v.i = i; return v;
}

static inline CorvusVal corvus_flo(double f) {
    CorvusVal v; v.type = VAL_FLO; v.f = f; return v;
}

static inline CorvusVal corvus_str(const char* s) {
    CorvusVal v; v.type = VAL_STR;
    if (!s) { v.s = strdup(""); }
    else { v.s = strdup(s); }
    return v;
}

static inline CorvusVal corvus_func(CorvusFnPtr fn) {
    CorvusVal v; v.type = VAL_FUNC; v.fn = fn; return v;
}

static inline bool corvus_is_true(CorvusVal v) {
    switch (v.type) {
        case VAL_NULL: return false;
        case VAL_BOOL: return v.b;
        case VAL_INT:  return v.i != 0;
        case VAL_FLO:  return v.f != 0.0;
        case VAL_STR:  return v.s && strlen(v.s) > 0;
        case VAL_LIST: return v.l.length > 0;
        case VAL_DICT: return v.d.length > 0;
        case VAL_FUNC: return true;
        default: return false;
    }
}

static void corvus_print_val(CorvusVal v);

static inline void corvus_print_dict(CorvusDict d) {
    printf("{");
    for (size_t k = 0; k < d.length; k++) {
        printf("'%s': ", d.keys[k]);
        if (d.vals[k].type == VAL_STR) {
            printf("'%s'", d.vals[k].s);
        } else {
            corvus_print_val(d.vals[k]);
        }
        if (k + 1 < d.length) printf(", ");
    }
    printf("}");
}

static void corvus_print_val(CorvusVal v) {
    switch (v.type) {
        case VAL_NULL: printf("null"); break;
        case VAL_BOOL: printf("%s", v.b ? "true" : "false"); break;
        case VAL_INT:  printf("%lld", v.i); break;
        case VAL_FLO:  printf("%g", v.f); break;
        case VAL_STR:  printf("%s", v.s ? v.s : ""); break;
        case VAL_FUNC: printf("<function>"); break;
        case VAL_LIST: {
            printf("[");
            for (size_t k = 0; k < v.l.length; k++) {
                if (v.l.items[k].type == VAL_STR) {
                    printf("'%s'", v.l.items[k].s);
                } else {
                    corvus_print_val(v.l.items[k]);
                }
                if (k + 1 < v.l.length) printf(", ");
            }
            printf("]");
            break;
        }
        case VAL_DICT: {
            corvus_print_dict(v.d);
            break;
        }
    }
}

static inline CorvusVal corvus_add(CorvusVal a, CorvusVal b) {
    if (a.type == VAL_INT && b.type == VAL_INT) return corvus_int(a.i + b.i);
    if ((a.type == VAL_INT || a.type == VAL_FLO) && (b.type == VAL_INT || b.type == VAL_FLO)) {
        double da = (a.type == VAL_FLO) ? a.f : (double)a.i;
        double db = (b.type == VAL_FLO) ? b.f : (double)b.i;
        return corvus_flo(da + db);
    }
    if (a.type == VAL_STR || b.type == VAL_STR) {
        char buf1[64], buf2[64];
        const char *s1 = (a.type == VAL_STR) ? a.s : (snprintf(buf1, 64, "%lld", a.i), buf1);
        const char *s2 = (b.type == VAL_STR) ? b.s : (snprintf(buf2, 64, "%lld", b.i), buf2);
        size_t len = strlen(s1) + strlen(s2) + 1;
        char* out = (char*)malloc(len);
        strcpy(out, s1);
        strcat(out, s2);
        CorvusVal v; v.type = VAL_STR; v.s = out;
        return v;
    }
    if (a.type == VAL_LIST && b.type == VAL_LIST) {
        size_t n = a.l.length + b.l.length;
        CorvusVal res; res.type = VAL_LIST; res.l.length = n; res.l.capacity = n;
        res.l.items = (CorvusVal*)malloc(sizeof(CorvusVal) * (n > 0 ? n : 1));
        memcpy(res.l.items, a.l.items, sizeof(CorvusVal) * a.l.length);
        memcpy(res.l.items + a.l.length, b.l.items, sizeof(CorvusVal) * b.l.length);
        return res;
    }
    return corvus_int(a.i + b.i);
}

static inline CorvusVal corvus_sub(CorvusVal a, CorvusVal b) {
    if (a.type == VAL_INT && b.type == VAL_INT) return corvus_int(a.i - b.i);
    double da = (a.type == VAL_FLO) ? a.f : (double)a.i;
    double db = (b.type == VAL_FLO) ? b.f : (double)b.i;
    return corvus_flo(da - db);
}

static inline CorvusVal corvus_mul(CorvusVal a, CorvusVal b) {
    if (a.type == VAL_INT && b.type == VAL_INT) return corvus_int(a.i * b.i);
    double da = (a.type == VAL_FLO) ? a.f : (double)a.i;
    double db = (b.type == VAL_FLO) ? b.f : (double)b.i;
    return corvus_flo(da * db);
}

static inline CorvusVal corvus_div(CorvusVal a, CorvusVal b) {
    double da = (a.type == VAL_FLO) ? a.f : (double)a.i;
    double db = (b.type == VAL_FLO) ? b.f : (double)b.i;
    if (db == 0.0) {
        fprintf(stderr, "[Corvus Panic]: Division by zero.\n");
        exit(1);
    }
    if (a.type == VAL_INT && b.type == VAL_INT && (a.i % b.i == 0)) {
        return corvus_int(a.i / b.i);
    }
    return corvus_flo(da / db);
}

static inline CorvusVal corvus_mod(CorvusVal a, CorvusVal b) {
    if (b.i == 0) {
        fprintf(stderr, "[Corvus Panic]: Modulo by zero.\n");
        exit(1);
    }
    return corvus_int(a.i % b.i);
}

static inline CorvusVal corvus_pow(CorvusVal a, CorvusVal b) {
    double da = (a.type == VAL_FLO) ? a.f : (double)a.i;
    double db = (b.type == VAL_FLO) ? b.f : (double)b.i;
    double res = pow(da, db);
    if (a.type == VAL_INT && b.type == VAL_INT && b.i >= 0) return corvus_int((long long)res);
    return corvus_flo(res);
}

static inline CorvusVal corvus_eq(CorvusVal a, CorvusVal b) {
    if (a.type != b.type) return corvus_bool(false);
    if (a.type == VAL_NULL) return corvus_bool(true);
    if (a.type == VAL_BOOL) return corvus_bool(a.b == b.b);
    if (a.type == VAL_INT)  return corvus_bool(a.i == b.i);
    if (a.type == VAL_FLO)  return corvus_bool(a.f == b.f);
    if (a.type == VAL_STR)  return corvus_bool(strcmp(a.s, b.s) == 0);
    return corvus_bool(false);
}

static inline CorvusVal corvus_neq(CorvusVal a, CorvusVal b) {
    CorvusVal eq = corvus_eq(a, b);
    return corvus_bool(!eq.b);
}

static inline CorvusVal corvus_lt(CorvusVal a, CorvusVal b) {
    if (a.type == VAL_INT && b.type == VAL_INT) return corvus_bool(a.i < b.i);
    double da = (a.type == VAL_FLO) ? a.f : (double)a.i;
    double db = (b.type == VAL_FLO) ? b.f : (double)b.i;
    return corvus_bool(da < db);
}

static inline CorvusVal corvus_lte(CorvusVal a, CorvusVal b) {
    if (a.type == VAL_INT && b.type == VAL_INT) return corvus_bool(a.i <= b.i);
    double da = (a.type == VAL_FLO) ? a.f : (double)a.i;
    double db = (b.type == VAL_FLO) ? b.f : (double)b.i;
    return corvus_bool(da <= db);
}

static inline CorvusVal corvus_gt(CorvusVal a, CorvusVal b) {
    return corvus_lt(b, a);
}

static inline CorvusVal corvus_gte(CorvusVal a, CorvusVal b) {
    return corvus_lte(b, a);
}

static inline CorvusVal corvus_len(CorvusVal v) {
    if (v.type == VAL_STR) return corvus_int(strlen(v.s));
    if (v.type == VAL_LIST) return corvus_int(v.l.length);
    if (v.type == VAL_DICT) return corvus_int(v.d.length);
    return corvus_int(0);
}

static inline CorvusVal corvus_make_list(CorvusVal* items, size_t count) {
    CorvusVal v;
    v.type = VAL_LIST;
    v.l.length = count;
    v.l.capacity = count > 4 ? count : 4;
    v.l.items = (CorvusVal*)malloc(sizeof(CorvusVal) * v.l.capacity);
    if (items && count > 0) {
        memcpy(v.l.items, items, sizeof(CorvusVal) * count);
    }
    return v;
}

static inline void corvus_list_add(CorvusVal* list, CorvusVal item) {
    if (list->type != VAL_LIST) return;
    if (list->l.length >= list->l.capacity) {
        list->l.capacity = (list->l.capacity == 0) ? 4 : list->l.capacity * 2;
        list->l.items = (CorvusVal*)realloc(list->l.items, sizeof(CorvusVal) * list->l.capacity);
    }
    list->l.items[list->l.length++] = item;
}

static inline CorvusVal corvus_list_pop(CorvusVal* list) {
    if (list->type != VAL_LIST || list->l.length == 0) return corvus_null();
    return list->l.items[--list->l.length];
}

static inline CorvusVal corvus_make_dict(const char** keys, CorvusVal* vals, size_t count) {
    CorvusVal v;
    v.type = VAL_DICT;
    v.d.length = count;
    v.d.capacity = count > 4 ? count : 4;
    v.d.keys = (char**)malloc(sizeof(char*) * v.d.capacity);
    v.d.vals = (CorvusVal*)malloc(sizeof(CorvusVal) * v.d.capacity);
    for (size_t k = 0; k < count; k++) {
        v.d.keys[k] = strdup(keys[k]);
        v.d.vals[k] = vals[k];
    }
    return v;
}

static inline CorvusVal corvus_dict_get(CorvusVal dict, CorvusVal key) {
    if (dict.type != VAL_DICT || key.type != VAL_STR) return corvus_null();
    for (size_t k = 0; k < dict.d.length; k++) {
        if (strcmp(dict.d.keys[k], key.s) == 0) {
            return dict.d.vals[k];
        }
    }
    return corvus_null();
}

static inline void corvus_dict_set(CorvusVal* dict, CorvusVal key, CorvusVal val) {
    if (dict->type != VAL_DICT || key.type != VAL_STR) return;
    for (size_t k = 0; k < dict->d.length; k++) {
        if (strcmp(dict->d.keys[k], key.s) == 0) {
            dict->d.vals[k] = val;
            return;
        }
    }
    if (dict->d.length >= dict->d.capacity) {
        dict->d.capacity = (dict->d.capacity == 0) ? 4 : dict->d.capacity * 2;
        dict->d.keys = (char**)realloc(dict->d.keys, sizeof(char*) * dict->d.capacity);
        dict->d.vals = (CorvusVal*)realloc(dict->d.vals, sizeof(CorvusVal) * dict->d.capacity);
    }
    dict->d.keys[dict->d.length] = strdup(key.s);
    dict->d.vals[dict->d.length] = val;
    dict->d.length++;
}

static inline CorvusVal corvus_index(CorvusVal target, CorvusVal idx) {
    if (target.type == VAL_LIST) {
        long long i = idx.i;
        if (i < 0) i += target.l.length;
        if (i < 0 || (size_t)i >= target.l.length) {
            fprintf(stderr, "[Corvus Panic]: List index out of range.\n");
            exit(1);
        }
        return target.l.items[i];
    }
    if (target.type == VAL_DICT) {
        return corvus_dict_get(target, idx);
    }
    if (target.type == VAL_STR) {
        long long i = idx.i;
        size_t len = strlen(target.s);
        if (i < 0) i += len;
        if (i < 0 || (size_t)i >= len) return corvus_null();
        char buf[2];
        buf[0] = target.s[i];
        buf[1] = 0;
        return corvus_str(buf);
    }
    return corvus_null();
}

/* Native 2D Matrix Multiplication (@ Operator) */
static inline CorvusVal corvus_matmul(CorvusVal A, CorvusVal B) {
    if (A.type != VAL_LIST || B.type != VAL_LIST || A.l.length == 0 || B.l.length == 0) {
        fprintf(stderr, "[Corvus Panic]: Incompatible operands for matrix multiplication @.\n");
        exit(1);
    }
    size_t rows_A = A.l.length;
    CorvusVal first_row_A = A.l.items[0];
    if (first_row_A.type != VAL_LIST) {
        fprintf(stderr, "[Corvus Panic]: Left operand of @ must be a 2D matrix.\n");
        exit(1);
    }
    size_t cols_A = first_row_A.l.length;
    size_t rows_B = B.l.length;
    CorvusVal first_row_B = B.l.items[0];
    if (first_row_B.type != VAL_LIST) {
        fprintf(stderr, "[Corvus Panic]: Right operand of @ must be a 2D matrix.\n");
        exit(1);
    }
    size_t cols_B = first_row_B.l.length;
    if (cols_A != rows_B) {
        fprintf(stderr, "[Corvus Panic]: Dimension mismatch for @: %zu != %zu\n", cols_A, rows_B);
        exit(1);
    }

    CorvusVal result = corvus_make_list(NULL, 0);
    for (size_t r = 0; r < rows_A; r++) {
        CorvusVal row_out = corvus_make_list(NULL, 0);
        CorvusVal row_a = A.l.items[r];
        for (size_t c = 0; c < cols_B; c++) {
            double dot = 0.0;
            bool is_all_int = true;
            for (size_t k = 0; k < cols_A; k++) {
                CorvusVal el_a = row_a.l.items[k];
                CorvusVal el_b = B.l.items[k].l.items[c];
                double va = (el_a.type == VAL_FLO) ? el_a.f : (double)el_a.i;
                double vb = (el_b.type == VAL_FLO) ? el_b.f : (double)el_b.i;
                if (el_a.type == VAL_FLO || el_b.type == VAL_FLO) is_all_int = false;
                dot += va * vb;
            }
            if (is_all_int) {
                corvus_list_add(&row_out, corvus_int((long long)dot));
            } else {
                corvus_list_add(&row_out, corvus_flo(dot));
            }
        }
        corvus_list_add(&result, row_out);
    }
    return result;
}

/* Built-in Library Functions */
static inline CorvusVal corvus_sum(CorvusVal lis) {
    if (lis.type != VAL_LIST) return corvus_int(0);
    double total = 0.0;
    bool is_flo = false;
    for (size_t k = 0; k < lis.l.length; k++) {
        CorvusVal it = lis.l.items[k];
        if (it.type == VAL_FLO) { is_flo = true; total += it.f; }
        else if (it.type == VAL_INT) { total += (double)it.i; }
    }
    return is_flo ? corvus_flo(total) : corvus_int((long long)total);
}

static inline CorvusVal corvus_min(CorvusVal a, CorvusVal b) {
    return corvus_is_true(corvus_lt(a, b)) ? a : b;
}

static inline CorvusVal corvus_max(CorvusVal a, CorvusVal b) {
    return corvus_is_true(corvus_gt(a, b)) ? a : b;
}

static inline CorvusVal corvus_abs(CorvusVal v) {
    if (v.type == VAL_INT) return corvus_int(v.i < 0 ? -v.i : v.i);
    if (v.type == VAL_FLO) return corvus_flo(fabs(v.f));
    return v;
}

static inline CorvusVal corvus_round(CorvusVal v, CorvusVal decimals) {
    double factor = pow(10.0, (double)decimals.i);
    double val = (v.type == VAL_FLO) ? v.f : (double)v.i;
    double rounded = round(val * factor) / factor;
    return (decimals.i == 0) ? corvus_int((long long)rounded) : corvus_flo(rounded);
}

static inline CorvusVal corvus_type_fn(CorvusVal v) {
    switch (v.type) {
        case VAL_NULL: return corvus_str("null");
        case VAL_BOOL: return corvus_str("bool");
        case VAL_INT:  return corvus_str("int");
        case VAL_FLO:  return corvus_str("flo");
        case VAL_STR:  return corvus_str("str");
        case VAL_LIST: return corvus_str("lis");
        case VAL_DICT: return corvus_str("dic");
        case VAL_FUNC: return corvus_str("func");
        default:       return corvus_str("any");
    }
}

static inline CorvusVal corvus_range(CorvusVal start, CorvusVal stop, CorvusVal step) {
    CorvusVal res = corvus_make_list(NULL, 0);
    long long st = start.i;
    long long sp = stop.i;
    long long inc = step.i == 0 ? 1 : step.i;
    if (inc > 0) {
        for (long long cur = st; cur < sp; cur += inc) {
            corvus_list_add(&res, corvus_int(cur));
        }
    } else {
        for (long long cur = st; cur > sp; cur += inc) {
            corvus_list_add(&res, corvus_int(cur));
        }
    }
    return res;
}

static inline CorvusVal corvus_str_upper(CorvusVal s) {
    if (s.type != VAL_STR) return s;
    char* copy = strdup(s.s);
    for (size_t k = 0; copy[k]; k++) copy[k] = (char)toupper((unsigned char)copy[k]);
    CorvusVal out; out.type = VAL_STR; out.s = copy;
    return out;
}

static inline CorvusVal corvus_str_lower(CorvusVal s) {
    if (s.type != VAL_STR) return s;
    char* copy = strdup(s.s);
    for (size_t k = 0; copy[k]; k++) copy[k] = (char)tolower((unsigned char)copy[k]);
    CorvusVal out; out.type = VAL_STR; out.s = copy;
    return out;
}

static inline CorvusVal corvus_str_trim(CorvusVal s) {
    if (s.type != VAL_STR) return s;
    const char* start = s.s;
    while (*start && isspace((unsigned char)*start)) start++;
    const char* end = s.s + strlen(s.s) - 1;
    while (end > start && isspace((unsigned char)*end)) end--;
    size_t len = (end >= start) ? (size_t)(end - start + 1) : 0;
    char* buf = (char*)malloc(len + 1);
    if (len > 0) memcpy(buf, start, len);
    buf[len] = 0;
    CorvusVal out; out.type = VAL_STR; out.s = buf;
    return out;
}

/* Standard Modules Emulation in C */
static inline CorvusVal corvus_math_sqrt(CorvusVal v) {
    double d = (v.type == VAL_FLO) ? v.f : (double)v.i;
    return corvus_flo(sqrt(d));
}

static inline CorvusVal corvus_math_sin(CorvusVal v) {
    double d = (v.type == VAL_FLO) ? v.f : (double)v.i;
    return corvus_flo(sin(d));
}

static inline CorvusVal corvus_math_cos(CorvusVal v) {
    double d = (v.type == VAL_FLO) ? v.f : (double)v.i;
    return corvus_flo(cos(d));
}

static inline CorvusVal corvus_chrono_now(void) {
    time_t t = time(NULL);
    return corvus_flo((double)t);
}

static inline CorvusVal corvus_chrono_sleep(CorvusVal ms) {
#if defined(_WIN32) || defined(_WIN64)
    Sleep((DWORD)ms.i);
#else
    usleep((useconds_t)(ms.i * 1000));
#endif
    return corvus_null();
}

static inline CorvusVal corvus_process_platform(void) {
#if defined(_WIN32) || defined(_WIN64)
    return corvus_str("win32");
#elif defined(__APPLE__)
    return corvus_str("darwin");
#else
    return corvus_str("linux");
#endif
}

/* Main Program Entry */
int main(int argc, char* argv[]) {
    corvus_print_val(corvus_str("==================================================")); printf(" "); printf("\n");;
    corvus_print_val(corvus_str("  Corvus Full Feature Parity Suite (v4.3)         ")); printf(" "); printf("\n");;
    corvus_print_val(corvus_str("==================================================")); printf(" "); printf("\n");;
    CorvusVal m1 = corvus_make_list((CorvusVal[]){corvus_make_list((CorvusVal[]){corvus_int(1LL), corvus_int(2LL)}, 2), corvus_make_list((CorvusVal[]){corvus_int(3LL), corvus_int(4LL)}, 2)}, 2);
    CorvusVal m2 = corvus_make_list((CorvusVal[]){corvus_make_list((CorvusVal[]){corvus_int(5LL), corvus_int(6LL)}, 2), corvus_make_list((CorvusVal[]){corvus_int(7LL), corvus_int(8LL)}, 2)}, 2);
    CorvusVal mm_res = corvus_matmul(m1, m2);
    corvus_print_val(corvus_str("Matrix Multiplication @ Result:")); printf(" "); printf("\n");;
    corvus_print_val(mm_res); printf(" "); printf("\n");;
    CorvusVal numbers = corvus_make_list((CorvusVal[]){corvus_int(10LL), corvus_int(20LL), corvus_int(30LL), corvus_int(40LL)}, 4);
    CorvusVal total = corvus_sum(numbers);
    CorvusVal smallest = corvus_min(corvus_int(15LL), corvus_int(8LL));
    CorvusVal largest = corvus_max(corvus_int(15LL), corvus_int(8LL));
    CorvusVal positive_val = corvus_abs(corvus_int(-99LL));
    CorvusVal rounded_val = corvus_round(corvus_flo(3.14159), corvus_int(2LL));
    CorvusVal type_name = corvus_type_fn(corvus_int(42LL));
    corvus_print_val(corvus_str("Builtins -> Sum:")); printf(" "); printf("\n");;
    corvus_print_val(total); printf(" "); printf("\n");;
    corvus_print_val(corvus_str("Builtins -> Min:")); printf(" "); printf("\n");;
    corvus_print_val(smallest); printf(" "); printf("\n");;
    corvus_print_val(corvus_str("Builtins -> Max:")); printf(" "); printf("\n");;
    corvus_print_val(largest); printf(" "); printf("\n");;
    corvus_print_val(corvus_str("Builtins -> Abs:")); printf(" "); printf("\n");;
    corvus_print_val(positive_val); printf(" "); printf("\n");;
    corvus_print_val(corvus_str("Builtins -> Round:")); printf(" "); printf("\n");;
    corvus_print_val(rounded_val); printf(" "); printf("\n");;
    corvus_print_val(corvus_str("Builtins -> Type:")); printf(" "); printf("\n");;
    corvus_print_val(type_name); printf(" "); printf("\n");;
    CorvusVal fruits = corvus_make_list((CorvusVal[]){corvus_str("apple"), corvus_str("banana")}, 2);
    corvus_list_add(&fruits, corvus_str("cherry"));
    corvus_print_val(corvus_str("List after add:")); printf(" "); printf("\n");;
    corvus_print_val(fruits); printf(" "); printf("\n");;
    corvus_print_val(corvus_str("List length:")); printf(" "); printf("\n");;
    corvus_print_val(corvus_len(fruits)); printf(" "); printf("\n");;
    CorvusVal removed = corvus_list_pop(&fruits);
    corvus_print_val(corvus_str("Popped element:")); printf(" "); printf("\n");;
    corvus_print_val(removed); printf(" "); printf("\n");;
    corvus_print_val(corvus_str("List after pop:")); printf(" "); printf("\n");;
    corvus_print_val(fruits); printf(" "); printf("\n");;
    CorvusVal config = corvus_make_dict((const char*[]){corvus_str("language").s, corvus_str("target").s}, (CorvusVal[]){corvus_str("Corvus"), corvus_str("native")}, 2);
    corvus_print_val(corvus_str("Dictionary config:")); printf(" "); printf("\n");;
    corvus_print_val(config); printf(" "); printf("\n");;
    corvus_print_val(corvus_str("Dictionary lookup ['language']:")); printf(" "); printf("\n");;
    corvus_print_val(corvus_index(config, corvus_str("language"))); printf(" "); printf("\n");;
    CorvusVal sample_str = corvus_str("corvus language");
    CorvusVal shout = corvus_str_upper(sample_str);
    corvus_print_val(corvus_str("String upper:")); printf(" "); printf("\n");;
    corvus_print_val(shout); printf(" "); printf("\n");;
    CorvusVal root_val = corvus_math_sqrt(corvus_flo(64.0));
    corvus_print_val(corvus_str("Math sqrt(64.0):")); printf(" "); printf("\n");;
    corvus_print_val(root_val); printf(" "); printf("\n");;
    CorvusVal status = (corvus_is_true(corvus_gt(total, corvus_int(50LL))) ? corvus_str("PASSED") : corvus_str("FAILED"));
    CorvusVal banner = corvus_add(corvus_add(corvus_add(corvus_str("Status: "), status), corvus_str(" | Final Score: ")), total);
    corvus_print_val(banner); printf(" "); printf("\n");;
    corvus_print_val(corvus_str("==================================================")); printf(" "); printf("\n");;
    corvus_print_val(corvus_str("[SUCCESS] Compiler-Interpreter Full Parity Verified!")); printf(" "); printf("\n");;
    corvus_print_val(corvus_str("==================================================")); printf(" "); printf("\n");;
    return 0;
}
